name: image_editor_plus
description: Image Editor Plugin with filters, drawing, text and emoji like stories.
version: 1.0.5
homepage: https://ensorta.com
repository: https://github.com/hsbijarniya/image_editor_plus

environment:
    sdk: ">=3.0.0 <4.0.0"
    flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  image_picker: ^1.0.0
  screenshot: ^2.1.0
  flutter_colorpicker: ^1.0.3
  extended_image: ^8.1.0
  image: ^4.1.3
  colorfilter_generator: ^0.0.8
  flutter_image_compress: ^2.0.3
  reorderables: ^0.6.0
  permission_handler: ^11.1.0
  signature: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
    uses-material-design: true
